// Layout
const layoutClasses = [
  "absolute",
  "fixed",
  "relative",
  "static",
  "sticky",
  "block",
  "inline",
  "inline-block",
  "hidden",
  "container",
  "container-xs",
  "container-sm",
  "container-md",
  "container-lg",
  "container-xl",
  "article",
  "dense",
  "z-0",
  "z-10",
  "z-20",
  "z-30",
  "z-40",
  "z-50",
  "z-isolate",
];

// Flex & Grid
const flexGridClasses = [
  "flex",
  "inline-flex",
  "flex-row",
  "flex-row-reverse",
  "flex-col",
  "flex-col-reverse",
  "flex-1",
  "flex-auto",
  "flex-initial",
  "flex-none",
  "items-start",
  "items-end",
  "items-center",
  "items-stretch",
  "justify-start",
  "justify-end",
  "justify-center",
  "justify-between",
  "justify-around",
  "justify-stretch",
  "gap-gutters",
  "gap-xs",
  "gap-sm",
  "gap-md",
  "gap-lg",
  "gap-xl",
  "grid",
  "grid-cols-1",
  "grid-cols-2",
  "grid-cols-3",
  "grid-cols-4",
  "grid-cols-5",
  "grid-cols-6",
  "place-items-start",
  "place-items-end",
  "place-items-center",
];

// Spacing
const spacingClasses = [
  "m-xs",
  "m-sm",
  "m-md",
  "m-lg",
  "m-xl",
  "mx-xs",
  "mx-sm",
  "mx-md",
  "mx-lg",
  "mx-xl",
  "my-xs",
  "my-sm",
  "my-md",
  "my-lg",
  "my-xl",
  "mt-xs",
  "mt-sm",
  "mt-md",
  "mt-lg",
  "mt-xl",
  "mb-xs",
  "mb-sm",
  "mb-md",
  "mb-lg",
  "mb-xl",
  "ml-xs",
  "ml-sm",
  "ml-md",
  "ml-lg",
  "ml-xl",
  "mr-xs",
  "mr-sm",
  "mr-md",
  "mr-lg",
  "mr-xl",
  "p-xs",
  "p-sm",
  "p-md",
  "p-lg",
  "p-xl",
  "px-xs",
  "px-sm",
  "px-md",
  "px-lg",
  "px-xl",
  "py-xs",
  "py-sm",
  "py-md",
  "py-lg",
  "py-xl",
  "py-section",
  "pt-xs",
  "pt-sm",
  "pt-md",
  "pt-lg",
  "pt-xl",
  "pb-xs",
  "pb-sm",
  "pb-md",
  "pb-lg",
  "pb-xl",
  "pl-xs",
  "pl-sm",
  "pl-md",
  "pl-lg",
  "pl-xl",
  "pr-xs",
  "pr-sm",
  "pr-md",
  "pr-lg",
  "pr-xl",
];

// Sizing & Aspect
const sizingClasses = [
  "aspect-square",
  "aspect-landscape",
  "aspect-portrait",
  "aspect-widescreen",
  "aspect-univisium",
  "aspect-anamorphic",
  "max-w-screen-xs",
  "max-w-screen-sm",
  "max-w-screen-md",
  "max-w-screen-lg",
  "max-w-screen-xl",
];

// Typography
const typographyClasses = [
  "heading-display",
  "heading-h1",
  "heading-h2",
  "heading-h3",
  "heading-h4",
  "heading-h5",
  "heading-h6",
  "text-xs",
  "text-sm",
  "text-md",
  "text-lg",
  "text-accent",
  "text-accent-foreground",
  "text-background",
  "text-balance",
  "text-card",
  "text-card-foreground",
  "text-eyebrow",
  "text-foreground",
  "text-info",
  "text-info-foreground",
  "text-input",
  "text-input-foreground",
  "text-muted",
  "text-muted-foreground",
  "text-pretty",
  "text-primary",
  "text-primary-foreground",
  "text-secondary",
  "text-secondary-foreground",
  "text-success",
  "text-success-foreground",
  "text-warning",
  "text-warning-foreground",
  "weight-body",
  "weight-bold",
  "weight-heading",
  "weight-mono",
  "line-clamp-3",
  "line-clamp-4",
  "line-clamp-5",
  "line-clamp-6",
  "sr-only",
];

// Color & Border
const colorBorderClasses = [
  "border",
  "border-t",
  "border-b",
  "border-l",
  "border-r",
  "border-dashed",
  "border-dotted",
  "border-accent",
  "border-border",
  "border-danger",
  "border-info",
  "border-primary",
  "border-secondary",
  "border-success",
  "border-warning",
  "ring",
  "shadow-xs",
  "shadow-sm",
  "shadow-md",
  "shadow-lg",
  "shadow-xl",
  "opacity-0",
  "opacity-25",
  "opacity-50",
  "opacity-75",
  "opacity-100",
];

// Object & Media
const objectMediaClasses = [
  "object-contain",
  "object-cover",
  "object-fill",
  "object-none",
  "object-scale-down",
  "avatar",
  "avatar-author",
];

// Button & Badge
const buttonBadgeClasses = [
  "button",
  "button-primary",
  "button-secondary",
  "button-accent",
  "button-ghost",
  "button-link",
  "button-icon",
  "button-dense",
  "button-text",
  "badge",
  "badge-primary",
  "badge-secondary",
  "badge-accent",
  "badge-ghost",
  "badge-link",
  "badge-label",
  "badge-dense",
];

// Utility & Misc
const utilityMiscClasses = [
  "overflow-hidden",
  "overflow-clip",
  "pointer-events-none",
];

// Order
const orderClasses = ["order-none", "order-first", "order-last"];

export const utilityClasses = [
  ...layoutClasses,
  ...flexGridClasses,
  ...spacingClasses,
  ...sizingClasses,
  ...typographyClasses,
  ...colorBorderClasses,
  ...objectMediaClasses,
  ...buttonBadgeClasses,
  ...utilityMiscClasses,
  ...orderClasses,
];
